- name: Prohibited swap
  shell: "swapoff -a && sysctl -w vm.swappiness=0"
  ignore_errors: true

- name: delete fstab swap conf
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
    backup: 'yes'

- name: Load kernel module
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack_ipv4
    - nf_conntrack
  ignore_errors: true

- name: Enable systemd to automatically load module services
  service:
    name: systemd-modules-load
    enabled: yes

- name: Added kernel module boot load configuration
  template:
    src: "k8s-modules.conf.j2"
    dest: "/etc/modules-load.d/k8s-modules.conf"

- name: Set system parameters
  template:
    src: "k8s-sysctl.conf.j2"
    dest: "/etc/sysctl.d/k8s-sysctl.conf"

- name: Effective system parameter
  shell: "sysctl -p /etc/sysctl.d/k8s-sysctl.conf"
  ignore_errors: true

- name: Set ulimits
  template:
    src: "k8s-ulimits.conf.j2"
    dest: "/etc/security/limits.d/k8s-ulimits.conf"

- name: Put SCTP on the kernel module blacklist
  copy:
    src: "sctp.conf"
    dest: "/etc/modprobe.d/sctp.conf"
